-- O mapa de Slack deixa de ser cadastro a cadastro e passa a ser o workspace.
--
-- O aviso de conclusão vinha falhando para quase todo mundo. O bot precisa do
-- id do Slack da pessoa, e só sabia obtê-lo de duas formas: pelo mapa
-- `slack_pessoas` — preenchido à mão, três nomes — ou por
-- `users.lookupByEmail`, que exige o escopo `users:read.email` que o app não
-- tem. Resultado: qualquer solicitante fora dos três nomes ficava sem aviso,
-- e a operação descobria pela mensagem de erro na tela.
--
-- A saída não é cadastrar um por um conforme falham. É carregar o diretório
-- inteiro de uma vez: são pessoas da própria empresa, o id do Slack é público
-- dentro do workspace, e quem solicita já está lá.
--
-- Isto NÃO substitui o escopo. Com ele, quem entrar na empresa amanhã é
-- encontrado sozinho; sem ele, alguém precisa rodar esta carga de novo. O que
-- muda é que o caso comum passa a funcionar hoje, em vez de esperar.
--
-- `do nothing` no conflito: entradas cadastradas à mão têm precedência,
-- porque cobrem quem usa um e-mail no formulário e outro no Slack — caso do
-- Gustavo, que o diretório sozinho nunca resolveria.

insert into slack_pessoas (email, slack_user_id, nome, origem) values
  -- @formaturismo.com.br
  ('bruna.barboza@formaturismo.com.br','U07M7GNDCQ1','Bruna Barboza','LOOKUP'),
  ('ketlin.resende@formaturismo.com.br','U0C0K5EGA3W','Ketlin Resende','LOOKUP'),
  ('eduardo.uehara@formaturismo.com.br','U07MNEG8484','Eduardo Uehara','LOOKUP'),
  ('jennifer.oliveira@formaturismo.com.br','U0ASBT5RCHH','Jennifer Oliveira','LOOKUP'),
  ('wellinton.matos@formaturismo.com.br','U0B084AV4Q4','Wellinton Matos','LOOKUP'),
  ('mariana.braga@formaturismo.com.br','U090S8URG4E','Mariana Braga','LOOKUP'),
  ('samira.batista@formaturismo.com.br','U0BCR0Y60SK','Samira Batista','LOOKUP'),
  ('livia.santos@formaturismo.com.br','U07MVEHJF9B','Livia Araujo','LOOKUP'),
  ('bruno.torres@formaturismo.com.br','U0AHDKBKZ6W','Bruno Torres','LOOKUP'),
  ('paulinho@formaturismo.com.br','U07M7GQ0Q8H','Paulo Fernandes','LOOKUP'),
  ('monique@formaturismo.com.br','U07MHL3EYGY','Monique','LOOKUP'),
  ('diego.miranda@formaturismo.com.br','U07N1JH7BG8','Diego Miranda','LOOKUP'),
  ('carolina.ribeiro@formaturismo.com.br','U07M7GP36BB','Carolina Ribeiro','LOOKUP'),
  ('bruna.coimbra@formaturismo.com.br','U07MJ00LY5A','Bruna Coimbra','LOOKUP'),
  ('eduarda.borges@formaturismo.com.br','U0B0YQD1VNU','Eduarda Borges','LOOKUP'),
  ('gabriel.perez@formaturismo.com.br','U07MC65QQ90','Gabriel Perez','LOOKUP'),
  ('larissa.oliveira@formaturismo.com.br','U07ML53384T','Larissa Oliveira','LOOKUP'),
  ('thaina.gomes@formaturismo.com.br','U08P3NRG7KR','Thaina Gomes','LOOKUP'),
  ('anderson.silva@formaturismo.com.br','U08H1M7QQ8N','Anderson Silva','LOOKUP'),
  ('janaina.oliveira@formaturismo.com.br','U07M7GP13K3','Janaina Oliveira','LOOKUP'),
  ('denis.cruz@formaturismo.com.br','U07LZEBRGE7','Denis Augusto','LOOKUP'),
  ('julia.sales@formaturismo.com.br','U07LXB7F1FE','Julia Sales','LOOKUP'),
  ('marina.claro@formaturismo.com.br','U07MQHQTWJ0','Marina Claro','LOOKUP'),
  ('rafael.kinoshita@formaturismo.com.br','U07MCJ2D001','Rafael Kinoshita','LOOKUP'),
  ('alice.crepaldi@formaturismo.com.br','U0B3ECG2Y5A','Alice Crepaldi','LOOKUP'),
  ('tati.cardoso@formaturismo.com.br','U07MSHN0NN5','Tati Cardoso','LOOKUP'),
  ('paulo.bispo@formaturismo.com.br','U0BR2MPNCBU','Paulo Bispo','LOOKUP'),
  ('ilana@formaturismo.com.br','U07M7GQ3ZAM','Ilana Pitanga','LOOKUP'),
  ('robson.freire@formaturismo.com.br','U08Q40NUQNR','Robson Freire','LOOKUP'),
  ('marcella.felipe@formaturismo.com.br','U083XQEEE8Y','Marcella Felipe','LOOKUP'),
  ('mateus.nicolas@formaturismo.com.br','U0BL10ENANR','Mateus Hamed','LOOKUP'),
  ('camila.correia@formaturismo.com.br','U07LXB9CCG4','Camila Correia','LOOKUP'),
  ('nicolas.domingues@formaturismo.com.br','U07M2CQ43NG','Nicolas Domingues','LOOKUP'),
  ('felipe.carvalho@formaturismo.com.br','U07MCJ4EQLR','Felipe Carvalho','LOOKUP'),
  ('marcelo.lucoveis@formaturismo.com.br','U07M7GQ26BB','Marcelo Lucoveis','LOOKUP'),
  ('renan.beleza@formaturismo.com.br','U07N9L5GXMW','Renan Beleza','LOOKUP'),
  ('esther@formaturismo.com.br','U08S3F5U9NH','Esther','LOOKUP'),
  ('marli.santos@formaturismo.com.br','U0B3ESCG5M2','Marli Santos','LOOKUP'),
  ('karinna.paixao@formaturismo.com.br','U07MD6WB1HC','Karinna Mendonca','LOOKUP'),
  ('fabiomedrado@formaturismo.com.br','U07LUPA1Y03','Fabio Medrado','LOOKUP'),
  ('priscila.elias@formaturismo.com.br','U07LZ68T0HZ','Priscila Elias','LOOKUP'),
  ('marcelo.prioste@formaturismo.com.br','U0BLJK594TV','Marcelo Prioste','LOOKUP'),
  ('kelly.stoque@formaturismo.com.br','U0BQWFD1B99','Kelly Stoque','LOOKUP'),
  ('giovana.almeida@formaturismo.com.br','U07MKSE814K','Giovana Almeida','LOOKUP'),
  ('marco.mussato@formaturismo.com.br','U0BD9N35S0L','Marco Mussato','LOOKUP'),
  ('rodolpho.santos@formaturismo.com.br','U07MNMJKNKA','Rodolpho Santos','LOOKUP'),
  ('tayna.sousa@formaturismo.com.br','U07P2B7HQ5A','Tayna Pereira','LOOKUP'),
  ('anna.genga@formaturismo.com.br','U07N47TMTJ4','Anna Genga','LOOKUP'),
  ('michele.paiva@formaturismo.com.br','U08LL94S7A5','Michele Soares','LOOKUP'),
  ('ana.toreti@formaturismo.com.br','U07MSDCHD34','Ana Paula Toreti','LOOKUP'),
  ('recepcao.adm@formaturismo.com.br','U07LSL6LQ6A','Recepcao','LOOKUP'),
  ('ana.luiza@formaturismo.com.br','U07M5ETL0HM','Ana Luiza','LOOKUP'),
  ('alice.marques@formaturismo.com.br','U09UVGQLDAS','Alice Alcantara','LOOKUP'),
  ('pietro.monitoria@formaturismo.com.br','U07LS0JRDE1','Pietro Riccioppo','LOOKUP'),
  ('camila.siqueira@formaturismo.com.br','U07LRS9D5A9','Camila Siqueira','LOOKUP'),
  ('iollanda.morais@formaturismo.com.br','U083MM9215X','Iollanda Alves','LOOKUP'),
  ('mariana@formaturismo.com.br','U07LUPA76BD','Mariana','LOOKUP'),
  ('camila.rodrigues@formaturismo.com.br','U07M7GQ5QBB','Camila Rodrigues','LOOKUP'),
  ('fabriccio@formaturismo.com.br','U07LXB9139S','Fabriccio','LOOKUP'),
  ('rosemere.prates@formaturismo.com.br','U07MR7XR0FK','Rose Prates','LOOKUP'),
  ('leticia.reis@formaturismo.com.br','U0AG15GFMPW','Leticia Reis','LOOKUP'),
  ('nina@formaturismo.com.br','U07MHL4REV6','Nina','LOOKUP'),
  ('beatriz.canedo@formaturismo.com.br','U07LXB8SV8U','Beatriz Canedo','LOOKUP'),
  ('joao.lima@formaturismo.com.br','U0AH77W7B99','Joao Victor Lima','LOOKUP'),
  ('bruno.lisboa@formaturismo.com.br','U09BU26C63A','Bruno Lisboa','LOOKUP'),
  ('vinicius.vach@formaturismo.com.br','U07M7M13WQ1','Vinicius Vach','LOOKUP'),
  ('tatyana.fervorini@formaturismo.com.br','U07M7GMUJ73','Tatyana Fervorini','LOOKUP'),
  ('thays.gargiam@formaturismo.com.br','U07LUBXDQ8K','Thays Gargiam','LOOKUP'),
  ('gabriel.dantas@formaturismo.com.br','U08EQCEQ3MX','Gabriel Dantas','LOOKUP'),
  ('matheus.lima@formaturismo.com.br','U08RQUVEYLB','Matheus Lima','LOOKUP'),
  ('gabriel.serrachioli@formaturismo.com.br','U0AHC2AL554','Gabriel Serrachioli','LOOKUP'),
  ('ana.oliveira@formaturismo.com.br','U0AM2RKPWJC','Ana Carolina Oliveira','LOOKUP'),
  ('yara.ciconello@formaturismo.com.br','U0BR6SN7L7M','Yara Ciconello','LOOKUP'),
  ('patricia.caldeira@formaturismo.com.br','U07MHL41WUQ','Patricia Caldeira','LOOKUP'),
  ('caroline.victoria@formaturismo.com.br','U07MNANHWGK','Carol Victoria','LOOKUP'),
  ('anderson@formaturismo.com.br','U07LS0H1MFF','Ander Sousa','LOOKUP'),
  ('edutavora@formaturismo.com.br','U07LEA48G1M','Eduardo Tavora','LOOKUP'),
  ('gustavo.ferreira@formaturismo.com.br','U07MS8K0CQK','Gustavo Ferreira','LOOKUP'),
  ('thomas.santos@formaturismo.com.br','U07MZFJSRUZ','Thomas Caetano','LOOKUP'),
  ('beatriz.leite@formaturismo.com.br','U07MMMJPC11','Beatriz Leite','LOOKUP'),
  ('rafaella.tardelli@formaturismo.com.br','U07N7HLPYSY','Rafaella Herbst','LOOKUP'),
  ('cananda.santos@formaturismo.com.br','U07MF8L4KPG','Cananda Santos','LOOKUP'),
  ('miqueias.souza@formaturismo.com.br','U0AHHMWUB7W','Miqueias Nunes','LOOKUP'),
  ('atila.amancio@formaturismo.com.br','U07N995SPCY','Atila Amancio','LOOKUP'),
  ('julia.barbosa@formaturismo.com.br','U0B8782GJ12','Julia Barbosa','LOOKUP'),
  ('saude.forfun@formaturismo.com.br','U07VC9KQD47','Abzara Falz','LOOKUP'),
  ('daniel.silva@formaturismo.com.br','U07LEA20XMM','Daniel Rodrigues','LOOKUP'),
  ('marcella.fonseca@formaturismo.com.br','U07MQMS4M7B','Marcella Delain','LOOKUP'),
  ('samara.silva@formaturismo.com.br','U07LN7RLRU6','Samara Salvador','LOOKUP'),
  ('keisy.meireles@formaturismo.com.br','U08SD4DHP41','Keisy Meireles','LOOKUP'),
  ('nathalia.scarparo@formaturismo.com.br','U0BKY0YHGBV','Nathalia Scarparo','LOOKUP'),
  ('gabrielly.baldissera@formaturismo.com.br','U0AB3E18UHG','Gabrielly Peixoto','LOOKUP'),
  ('felipe.canato@formaturismo.com.br','U08RL0TTLS0','Felipe Canato','LOOKUP'),
  ('mauricio@formaturismo.com.br','U07LEA1L487','Mauricio Calasans','LOOKUP'),
  ('sydney@formaturismo.com.br','U07M7GNFHB3','Ney Costa','LOOKUP'),
  ('sac@formaturismo.com.br','U07M8LEPR6Z','SAC','LOOKUP'),
  ('vinicius.fernandes@formaturismo.com.br','U07MC9SDJ0J','Vinicius Fernandes','LOOKUP'),
  ('kaminski.starke@formaturismo.com.br','U07M2CPE7S8','Kaminski Starke','LOOKUP'),
  ('claudia.gomes@formaturismo.com.br','U08J2S2DLRX','Claudia Gomes','LOOKUP'),
  ('angelo@formaturismo.com.br','U07LMRKQX6J','Angelo Ruggero','LOOKUP'),
  ('jhonata.costa@formaturismo.com.br','U0BLWCNUN4Q','Jhonata Costa','LOOKUP'),
  ('nathalia.chouzende@formaturismo.com.br','U07LEA2FYQP','Nathalia Chouzende','LOOKUP'),
  ('ana.frederico@formaturismo.com.br','U07LMSEK1FY','Ana Frederico','LOOKUP'),
  ('isabelly.peniche@formaturismo.com.br','U0BQMBJGV1V','Isabelly Peniche','LOOKUP'),
  ('nicole.oliveira@formaturismo.com.br','U07NAKSRRCY','Nicole Oliveira','LOOKUP'),
  ('julia.nussbaumer@formaturismo.com.br','U0C0K60Q8FQ','Julia Nussbaumer','LOOKUP'),
  ('andressa.bonetto@formaturismo.com.br','U090PNGMGDQ','Andressa Bonetto','LOOKUP'),
  ('thais.viana@formaturismo.com.br','U07M2CNSA1J','Thais Viana','LOOKUP'),
  ('bianca.santana@formaturismo.com.br','U08NDT50TR7','Bianca Santana','LOOKUP'),
  ('rodrigo.cesare@formaturismo.com.br','U07LUS8LSUS','Rodrigo Cesare','LOOKUP'),
  ('gabriel.anjos@formaturismo.com.br','U07QLNH3UM6','Gabriel Anjos','LOOKUP'),
  ('vitoria.salustiano@formaturismo.com.br','U07MKUJQ9PU','Vitoria Salustiano','LOOKUP'),
  ('mirella.vital@formaturismo.com.br','U07MLRYBE3V','Mirella Vital','LOOKUP'),
  ('lavinya.silva@formaturismo.com.br','U08PWAG6PGC','Lavinya Silva','LOOKUP'),
  ('nathalia.cassola@formaturismo.com.br','U07MFQSQ2J2','Nathalia Cassola','LOOKUP'),
  ('janlucas@formaturismo.com.br','U07LUTMJBA7','Jan Lucas','LOOKUP'),
  ('rafael.schafer@formaturismo.com.br','U0AHA70VDHB','Rafael Schafer','LOOKUP'),
  ('ricardo.silva@formaturismo.com.br','U07PV4GKNCA','Ricardo Henrique','LOOKUP'),
  ('kemely@formaturismo.com.br','U0BTZK72QRZ','Kemely Berthi','LOOKUP'),
  ('matheus.guimaraes@formaturismo.com.br','U07M6CUSNVD','Matheus Guimaraes','LOOKUP'),
  ('ewerton.oliveira@formaturismo.com.br','U08RS7T5UHY','Ewerton Moreira','LOOKUP'),
  ('julia.moraes@formaturismo.com.br','U0BELT850KB','Julia Moraes','LOOKUP'),
  ('kelvin.dibi@formaturismo.com.br','U0AHDKE39BL','Kelvin Dibi','LOOKUP'),
  ('nayara.valadares@formaturismo.com.br','U0BTAJV0YRH','Nayara Valadares','LOOKUP'),
  ('mariana.ramos@formaturismo.com.br','U0AHBHNSCKY','Mariana Ramos','LOOKUP'),
  ('luan.fernandes@formaturismo.com.br','U07M7M16TKK','Luan Fernandes','LOOKUP'),
  ('estoque.depp@formaturismo.com.br','U07MSAJDFA7','Eduarda Miranda','LOOKUP'),
  ('matheus.inter@formaturismo.com.br','U07MJ0L0R5M','Matheus Barsi','LOOKUP'),
  ('caio.vieira@formaturismo.com.br','U07M7M1B0P3','Caio Vieira','LOOKUP'),
  ('fernando.bsb@formaturismo.com.br','U07MHQFV1JL','Fernando Camilo','LOOKUP'),
  ('taina.aguilar@formaturismo.com.br','U0BSA0JQUVC','Taina Aguilar','LOOKUP'),
  ('fabio.leite@formaturismo.com.br','U07MHQFPQ48','Fabio Leite','LOOKUP'),
  ('rodrigo.mattia@formaturismo.com.br','U07LUPA5GTV','Rodrigo De Mattia','LOOKUP'),
  ('daniela.roman@formaturismo.com.br','U0AGSD8USSY','Daniela Roman','LOOKUP'),
  ('felipe.mattarazzo@formaturismo.com.br','U08B95BBBM5','Felipe Mattarazzo','LOOKUP'),
  ('fabio.oliveira@formaturismo.com.br','U07M7M18W8H','Fabio Oliveira','LOOKUP'),
  ('beatriz.barreiros@formaturismo.com.br','U09KV877H6E','Beatriz Barreiros','LOOKUP'),
  ('eduardo.lara@formaturismo.com.br','U07LXEX0K8C','Eduardo Lara','LOOKUP'),
  ('gabriela.santana@formaturismo.com.br','U09AL6SBBS5','Gabriela Santana','LOOKUP'),
  ('cesar@formaturismo.com.br','U07LN7S5BJA','Cesar Leonel','LOOKUP'),
  ('alexvelloso@formaturismo.com.br','U07LXFM334L','Alex Velloso','LOOKUP'),
  ('saude.atibaia@formaturismo.com.br','U07P7NE9NSD','Saude Atibaia','LOOKUP'),
  ('rodrigo@formaturismo.com.br','U07LS0JUUQ5','Rodrigo Batuta','LOOKUP'),
  ('shai@formaturismo.com.br','U07MHQFGXGQ','Shai','LOOKUP'),
  ('henrique.souza@formaturismo.com.br','U09Q03ZGWUE','Henrique Souza','LOOKUP'),
  ('amanda.caffeo@formaturismo.com.br','U07P7CAB3RP','Amanda Caffeo','LOOKUP'),
  ('pedro.santos@formaturismo.com.br','U0BQXNW6UBH','Pedro Hermes','LOOKUP'),
  ('marcela@formaturismo.com.br','U082UN2BG5A','Marcela Almeida','LOOKUP'),
  ('orlando.silva@formaturismo.com.br','U07S9UC72BF','Orlando Silva','LOOKUP'),
  ('maria.luiza@formaturismo.com.br','U0BRBKV3UFK','Maria Luiza Goncalves','LOOKUP'),
  ('kelly.soares@formaturismo.com.br','U07RRQMKB51','Kelly Soares','LOOKUP'),
  ('nathalia.nascimento@formaturismo.com.br','U0ASG46MC9X','Nathalia Nascimento','LOOKUP'),
  ('mauricio.libere@formaturismo.com.br','U07LN7RNMV4','Mauricio Libere','LOOKUP'),
  ('renato@formaturismo.com.br','U07PEN52SNP','Renato Costa','LOOKUP'),

  -- @formahomolog.com.br
  ('bruno@formahomolog.com.br','U07LJ5UT3FH','Bruno Mendes','LOOKUP'),
  ('carol@formahomolog.com.br','U024VCXUE4D','Carolina Guariso','LOOKUP'),
  ('anacarolina@formahomolog.com.br','U07LS3L4J5C','Ana Carolina','LOOKUP'),
  ('gabriel.vilela@formahomolog.com.br','U07M1L0UU92','Gabriel Vilela','LOOKUP'),
  ('luana.bueno@formahomolog.com.br','U07M1B37T0U','Luana Bueno','LOOKUP'),
  ('leonardo.azeredo@formahomolog.com.br','U0ASMR08ASY','Leonardo Azeredo','LOOKUP'),
  ('sorriso@formahomolog.com.br','U0AUYEYNTNV','Sorriso Nunes','LOOKUP'),
  ('isabela.balduino@formahomolog.com.br','U07LKMB1DFZ','Isabela Balduino','LOOKUP'),
  ('luana.dardes@formahomolog.com.br','U07LJ951JUF','Luana Paulin','LOOKUP'),
  ('tales.xavier@formahomolog.com.br','U07MP0SPHLY','Tales Xavier','LOOKUP'),
  ('bruna@formahomolog.com.br','U07LURNNN75','Bruna','LOOKUP'),
  ('robson@formahomolog.com.br','U02TBRD7UG2','Robson Fulaneti','LOOKUP'),
  ('luiza.aparicio@formahomolog.com.br','U07LX6D1LMT','Luiza Carvalho','LOOKUP'),
  ('joao.ribeiro@formahomolog.com.br','U08B44AP4G4','Joao Ribeiro','LOOKUP'),
  ('pedro.lemos@formahomolog.com.br','U07LW252URK','Pedro Lemos','LOOKUP'),
  ('tayna.rodrigues@formahomolog.com.br','U07LZ6RQQFL','Tayna Rodrigues','LOOKUP'),
  ('marcelo.dias@formahomolog.com.br','U07MBRE7UMP','Marcelo Dias','LOOKUP'),
  ('gustavo@formahomolog.com.br','U07LX8P8Q76','Gustavo Bueno','LOOKUP'),
  ('ana.ramos@formahomolog.com.br','U09EJ1A348H','Ana Ramos','LOOKUP'),
  ('gabriel.almeida@formahomolog.com.br','U08B8TL2258','Gabriel Almeida','LOOKUP'),
  ('beatriz.souza@formahomolog.com.br','U07MMMG91KJ','Beatriz Souza','LOOKUP'),
  ('vitor.finoto@formahomolog.com.br','U07LJ90BKSB','Vitor Finoto','LOOKUP'),
  ('renata.rodrigues@formahomolog.com.br','U07LZ2LGAKD','Renata Rodrigues','LOOKUP'),
  ('fernanda.araujo@formahomolog.com.br','U0BSXHZUSAE','Fernanda Araujo','LOOKUP'),
  ('lais.silva@formahomolog.com.br','U07LS99THB8','Lais Lima','LOOKUP'),
  ('publicidade@formahomolog.com.br','U085ZM463K7','Forma Informa','LOOKUP'),
  ('henrique@formahomolog.com.br','U01PDDSF1CK','Paulo Henrique','LOOKUP'),
  ('luiza@formahomolog.com.br','U07LX2QK7GC','Luiza Rey','LOOKUP'),
  ('laura@formahomolog.com.br','U07LX7AMWCU','Laura','LOOKUP'),
  ('ananda.paulino@formahomolog.com.br','U0A8V0ZNHLZ','Ananda Paulino','LOOKUP'),
  ('kelvin.trigoni@formahomolog.com.br','U01PDDT0WPM','Kelvin Trigoni','LOOKUP'),
  ('maria.julia@formahomolog.com.br','U0BR6SJ27LK','Maria Julia Venkli','LOOKUP'),
  ('saulo@formahomolog.com.br','U07LKNRJ4MD','Saulo Decris','LOOKUP'),
  ('eduardo@formahomolog.com.br','U010ES2BAG0','Eduardo Bachiega','LOOKUP'),
  ('joao@formahomolog.com.br','U07M78B0DTK','Joao','LOOKUP'),
  ('torres@formahomolog.com.br','U07LS3C85DL','Fernando Torres','LOOKUP'),
  ('bolacha@formahomolog.com.br','U07MHL3L89E','Bolacha','LOOKUP'),
  ('isabelle.valerio@formahomolog.com.br','U0B4EJ5ERTP','Isabelle Valerio','LOOKUP'),

  -- @colabformaturas.com.br
  ('rafael@colabformaturas.com.br','U07LX8Z4F7F','Rafael Gomes','LOOKUP'),

  -- @formaconhecer.com.br
  ('graciela@formaconhecer.com.br','U0BMU6K20JY','Graciela Lopes','LOOKUP'),
  ('beatriz.pereira@formaconhecer.com.br','U0BK52QPKJQ','Beatriz Pereira','LOOKUP'),
  ('suporte.operacional@formaconhecer.com.br','U0AT4B0SHTQ','Nathalia Orsi Scarparo','LOOKUP'),
  ('claudio.eugenio@formaconhecer.com.br','U07LXDQU2A0','Claudio Luiz Eugenio','LOOKUP'),
  ('agendamentosp@formaconhecer.com.br','U07M701FKFY','Zulaie Maria Lozano','LOOKUP'),
  ('marcelo.carao@formaconhecer.com.br','U07MHL43T4Y','Marcelo Carao','LOOKUP'),
  ('itamar@formaconhecer.com.br','U07MHEHJCEB','Itamar Fonseca','LOOKUP'),
  ('operacional.sp@formaconhecer.com.br','U07MCK0QGF4','Gabi Agrela','LOOKUP'),
  ('yasmin.gutieri@formaconhecer.com.br','U08PWA8MF7T','Yasmin Gutieri','LOOKUP'),
  ('marcela.almeida@formaconhecer.com.br','U08MYRFFHRN','Marcela','LOOKUP'),
  ('alexandre.caldas@formaconhecer.com.br','U07NH3BDG8Y','Alexandre Caldas','LOOKUP'),
  ('conhecer.pe@formaconhecer.com.br','U07MU60P09Z','Valquiria Cavalcante','LOOKUP'),
  ('emanuelle@formaconhecer.com.br','U08RW81HKJR','Emanuelle','LOOKUP'),
  ('operacional.pr@formaconhecer.com.br','U0BK4AJE1TK','Operacional PR','LOOKUP'),
  ('conhecer.rj@formaconhecer.com.br','U07NLGGDGH4','Barbara','LOOKUP'),

  -- @lojadaforma.com.br
  ('akira@lojadaforma.com.br','U08AS7KSG9M','Felipe Akira','LOOKUP'),
  ('caroline@lojadaforma.com.br','U08B6HG8WJF','Caroline','LOOKUP'),
  ('nathalya@lojadaforma.com.br','U08R21DTYDD','Nathalya','LOOKUP')
on conflict (email) do nothing;
